config/routes.rb
Rails.application.routes.draw do
  resources :follows
  resources :immunization_schedules, only: [:index, :new, :create, :show, :edit, :destroy] do
    member do
      patch 'update_status'
    end
  end

  resources :immunizations, only: [:index, :new, :create, :show, :edit, :destroy]
  resources :children do
    resources :immunizations
    resources :immunization_schedules do
      member do
        patch 'update_status' # Nested under `immunization_schedules` for updating immunization schedules
        post 'follow_up_call'
      end
    end
  end
  
  
  devise_for :medics
  get 'dashboard/index'
  post '/send_sms', to: 'children#send_sms'
  post '/welcome_sms', to: 'children#send_welcome_sms'
  # post 'immunization_schedule/follow_up_call'
  # post 'follows/follow_up_call'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :set_child, only: %i[ show edit update destroy ]

  # GET /children or /children.json
  def index
    if params[:name].present?
      search_term = "%#{params[:name].downcase}%"
      @children = Child.where("lower(baby_name) LIKE ?", search_term)
    else
      @children = Child.all
    end
  end
  

  # GET /children/1 or /children/1.json
  def show
    @child = Child.find(params[:id])
    @baby_schedules = @child.immunization_schedules
  end

  # GET /children/new
  def new
    @child = Child.new
  end

  # GET /children/1/edit
  def edit
  end

  def update_status
    @child = Child.find(params[:child_id]) # Use child_id here
    @schedule = @child.immunization_schedules.find(params[:id]) # Use id for immunization_schedule
    if @schedule.update(status: true)
      flash[:notice] = "Immunization status updated successfully."
    else
      flash[:error] = "Failed to update immunization status."
    end
    redirect_to child_path(@child)
  end  
  

  # POST /children or /children.json
  def create
    @child = Child.new(child_params)

    respond_to do |format|
      if @child.save
        send_sms(@child)
        format.html { redirect_to child_url(@child), notice: "Child was successfully created." }
        format.json { render :show, status: :created, location: @child }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /children/1 or /children/1.json
  def update
    respond_to do |format|
      if @child.update(child_params)
        format.html { redirect_to child_url(@child), notice: "Child was successfully updated." }
        format.json { render :show, status: :ok, location: @child }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1 or /children/1.json
  def destroy
    @child.destroy

    respond_to do |format|
      format.html { redirect_to children_url, notice: "Child was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child
      @child = Child.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def child_params
      params.require(:child).permit(:baby_name, :parent_name, :date_of_birth, :gender, :phone_number)
    end

    def send_sms(child)
      # Set your app credentials
      # username = "valeria"
      #   apikey = "a91bf656d1ef72542dcbfe7b650e1263c08616ca9a71bf32f304699541cf86ce"
        username = "Gvans"
        apikey = "f19a53547997899dd02428a43499c58a3eb7a5c9aabbf3d1ea4e93d8bfc517ab"
      
        # Initialize the SDK
        @AT = AfricasTalking::Initialize.new(username, apikey)
      
        sms = @AT.sms
      # Retrieve the Current user's details from the database
  
      # to = child.phone_number
      
      baby = child.baby_name
      parent = child.parent_name
      to = child.phone_number
      
        # Send the welcome message
        message = "Welcome, #{parent}! Get ready for Chanjo, your ultimate immunization reminder app for your precious little one, #{baby}. We'll ensure you never miss a vaccination appointment. Stay tuned for regular reminders and keep your baby protected!"
        
        # Set your shortCode or senderId
        # from = "Vaxx-Alerts"
      
        options = {
          "to" => to,
          "message" => message
          # "from" => from
        }
      
        begin
          # Send the SMS and retrieve the response
          response = sms.send(options)
      
          # Log success or any necessary information
          Rails.logger.info "SMS sent successfully"
        rescue AfricasTalking::AfricasTalkingException => ex
          # Log error or any necessary information
          Rails.logger.error "Failed to send SMS: #{ex.message}"
        end
        
      end


    #send sms
    def send_welcome_sms(child)
      username = "Gvans"
      apikey = "f19a53547997899dd02428a43499c58a3eb7a5c9aabbf3d1ea4e93d8bfc517ab"
    
      # Initialize the SDK
      @AT = AfricasTalking::Initialize.new(username, apikey)
    
      sms = @AT.sms
    
      baby = child.baby_name
      parent = child.parent_name
      phone_number = child.phone_number
      to = "+#{phone_number}"
    
      # Send the welcome message
      welcome_message = "Welcome, #{parent}! Get ready for Chanjo, your ultimate immunization reminder app for your precious little one, #{baby}. We'll ensure you never miss a vaccination appointment. Stay tuned for regular reminders and keep your baby protected!"
      sends_sms(sms, to, welcome_message)
    
      # Send the next appointment message
      next_appointment_message = generate_next_appointment_message(child)
      sends_sms(sms, to, next_appointment_message)
    end
    
    def sends_sms(sms, to, message)
      # Set your shortCode or senderId
      # from = "Vaxx-Alerts"
    
      options = {
        "to" => to,
        "message" => message,
        # "from" => from
      }
    
      begin
        # Send the SMS and retrieve the response
        response = sms.send(options)
    
        # Log success or any necessary information
        Rails.logger.info "SMS sent successfully"
      rescue AfricasTalking::AfricasTalkingException => ex
        # Log error or any necessary information
        Rails.logger.error "Failed to send SMS: #{ex.message}"
      end
    end
    
    def generate_next_appointment_message(child)
      baby = child.baby_name
      parent = child.parent_name
      date_of_birth = child.date_of_birth
    
      # Calculate the next immunization date and days left
      next_immunization_date, days_left, immunization_name = calculate_next_immunization(child)
    
      if next_immunization_date && days_left && immunization_name
        return "Dear #{parent}, the next immunization for Baby #{baby} is on #{next_immunization_date}. There are #{days_left} days left. Remember this will be #{immunization_name}"
      else
        return "No upcoming immunizations scheduled for Baby #{baby}"
      end
    end
    
    def calculate_next_immunization(child)
      date_of_birth = child.date_of_birth
    
      if (date_of_birth + 6.weeks) > Date.today
        next_immunization_date = date_of_birth + 6.weeks
        days_left = (next_immunization_date - Date.today).to_i
        immunization_name = "2nd Oral polio vaccine; DPT, Hepatitis B and HIB; Pneumococcal vaccine (PCV 10); Rotavirus vaccine (Rotarix)"
      elsif (date_of_birth + 10.weeks) > Date.today
        next_immunization_date = date_of_birth + 10.weeks
        days_left = (next_immunization_date - Date.today).to_i
        immunization_name = "3rd Oral polio vaccine; DPT, Hepatitis B and HIB; Pneumococcal vaccine (PCV 10); Rotavirus vaccine (Rotarix)"
      elsif (date_of_birth + 14.weeks) > Date.today
        next_immunization_date = date_of_birth + 14.weeks
        days_left = (next_immunization_date - Date.today).to_i
        immunization_name = "4th Oral polio vaccine; DPT, Hepatitis B and HIB; Pneumococcal vaccine (PCV 10)"
      elsif (date_of_birth + 26.weeks) > Date.today
        next_immunization_date = date_of_birth + 26.weeks
        days_left = (next_immunization_date - Date.today).to_i
        immunization_name = "Measles vaccine, Vitamin A"
      elsif (date_of_birth + 39.weeks) > Date.today
        next_immunization_date = date_of_birth + 39.weeks
        days_left = (next_immunization_date - Date.today).to_i
        immunization_name = "Measles vaccine, Yellow Fever vaccine"
      end
    
      return next_immunization_date, days_left, immunization_name
    end
  
end

app/helpers/children_helper.rb
module ChildrenHelper
end

app/views/children/_child.html.erb
<div id="<%= dom_id child %>">
  <p>
    <strong>Baby name:</strong>
    <%= child.baby_name %>
  </p>

  <p>
    <strong>Parent name:</strong>
    <%= child.parent_name %>
  </p>

  <p>
    <strong>Date of birth:</strong>
    <%= child.date_of_birth %>
  </p>

  <p>
    <strong>Gender:</strong>
    <%= child.gender %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= child.phone_number %>
  </p>

</div>

app/views/children/_form.html.erb
<%= form_with(model: child) do |form| %>
  <% if child.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
        <% child.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :baby_name %>
    <%= form.text_field :baby_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :parent_name %>
    <%= form.text_field :parent_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :date_of_birth %>
    <%= form.date_field :date_of_birth, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :gender %>
    <%= form.text_field :gender, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone_number, "Phone Number (start with 2547...)" %>
    <%= form.number_field :phone_number, class: "form-control" %>
  </div>
  <br />
  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
</form>
<% end %>

app/views/children/edit.html.erb
<h1>Editing child</h1>

<%= render "form", child: @child %>

<br>

<div>
  <%= link_to "Show this child", @child %> |
  <%= link_to "Back to children", children_path %>
</div>

app/views/children/index.html.erb
<div class="container-fluid">
  <div class="row">
    <!-- Sidebar -->
    <div class="col-md-3 col-xl-2 bg-light sidebar">
      <%= render partial: "shared/sidebar" %>
    </div>

    <!-- Main Content -->
    <div class="col-md-9 col-xl-10">
      <div class="main-content-container">
        <h1>Children List</h1>
        <div class="row">
          <div class="col-md-6">
            <%= form_with url: children_path, class: "search-form", method: :get do |form| %>
              <div class="input-group">
                <%= form.text_field :name, value: params[:name], class: "form-control", placeholder: "Search for a child by name" %>
                <div class="input-group-append">
                  <%= form.submit "Search", class: "btn btn-primary" %>
                </div>
              </div>
            <% end %>
          </div>
          <div class="col-md-6 text-right">
            <%= link_to "New Child", new_child_path, class: "btn btn-success" %>
          </div>
        </div>
        <br />
        <div class="table-responsive">
          <table class="table table-bordered">
            <thead>
              <tr>
                <th>Child Name</th>
                <th>Parent Name</th>
                <th>Date of Birth</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              <% @children.each do |child| %>
                <tr>
                  <td><%= child.baby_name %></td>
                  <td><%= child.parent_name %></td>
                  <td><%= child.date_of_birth %></td>
                  <td>
                    <%= link_to "View more", child, class: "btn btn-info btn-sm mr-1" %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/children/new.html.erb
<div class="container-fluid">
  <div class="row">
    <!-- Sidebar -->
    <div class="col-md-3 col-xl-2 bg-light sidebar">
      <%= render partial: "shared/sidebar" %>
    </div>
    
    <!-- Main Content -->
    <div class="col-md-9 col-xl-10">
      <div class="main-content-container">
        <h1>New child</h1>
        <div class="row">
          <div class="col-md-6">

            <%= render "form", child: @child %>

            <br />

            <div>
              <%= link_to "Back to children", children_path %>
            </div>
            </div>
            </div>
            </div>
            </div>
            </div>
            </div>

app/views/children/show.html.erb
<div class="row">
  <!-- Sidebar -->
  <div class="col-md-3 col-xl-2 bg-light sidebar">
    <%= render partial: "shared/sidebar" %>
  </div>
  
  <!-- Main Content -->
  <div class="col-md-9 col-xl-10">
    <div class="main-content-container">
      <!-- Child Details -->
      <div class="row">
        <div class="col-md-4">
          <%= render @child %>
          <div class="mt-3 button-container">
            <%= link_to "Back", children_path, class: "btn btn-primary btn-block" %>
            <%= link_to "Edit", edit_child_path(@child), class: "btn btn-secondary btn-block" %>
            <%= button_to "Destroy", @child, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-block" %>
          </div>
          <div class="mt-3">
            <%= button_to "Send SMS", send_sms_path(@child), method: :post, class: "btn btn-primary btn-block" %>
            <%= button_to "Send Welcome SMS", welcome_sms_path(child_id: @child.id), method: :post, class: "btn btn-primary btn-block" %>
            
          </div>
        </div>
        
        <!-- Immunization Schedule Table -->
        <div class="col-md-8">
          <h1 class="mb-3">Immunization schedules</h1>
          <% if @child.immunization_schedules.empty? %>
            <p>No immunization scheduled yet.</p>
            <%= link_to "Schedule Immunization", new_child_immunization_schedule_path(@child), class: "btn btn-primary btn-block" %>
          <% else %>
            <div class="table-responsive">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th>Immunization Name</th>
                    <th>Date</th>
                    <th>Status</th>
                  </tr>
                </thead>
                <tbody>
                  <% @child.immunization_schedules.each do |baby_schedule| %>
                    <tr>
                      <td><%= truncate(baby_schedule.vaxx_name, length: 30) %></td>
                      <td><%= baby_schedule.scheduled_date %></td>
                      <td>
                        <% if baby_schedule.status === true %>
                          <span class="btn btn-info btn-sm">Taken</span>
                        <% else %>
                          <%= form_with(model: baby_schedule, url: update_status_child_immunization_schedule_path(@child, baby_schedule), data: { 'turbo-method': :patch }) do |form| %>
                            <%= form.hidden_field :status, value: true %>
                            <%= form.submit "Mark as Taken", class: "btn btn-info btn-sm" %>
                          <% end %>
                        <% end %>
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
            <%= link_to "Add Immunization", new_child_immunization_path(@child), class: "btn btn-primary btn-block" %>
            <%= link_to "Schedule Immunization", new_child_immunization_schedule_path(@child), class: "btn btn-primary btn-block" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>