config/routes.rb
Rails.application.routes.draw do
  resources :follows
  resources :immunization_schedules, only: [:index, :new, :create, :show, :edit, :destroy] do
    member do
      patch 'update_status'
    end
  end

  resources :immunizations, only: [:index, :new, :create, :show, :edit, :destroy]
  resources :children do
    resources :immunizations
    resources :immunization_schedules do
      member do
        patch 'update_status' # Nested under `immunization_schedules` for updating immunization schedules
        post 'follow_up_call'
      end
    end
  end
  
  
  devise_for :medics
  get 'dashboard/index'
  post '/send_sms', to: 'children#send_sms'
  post '/welcome_sms', to: 'children#send_welcome_sms'
  # post 'immunization_schedule/follow_up_call'
  # post 'follows/follow_up_call'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary top-nav fixed-top">
  <div class="container-fluid">
    <%= link_to "Chanjo-Health", root_path, class: "navbar-brand nav-logo"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mx-auto mb-2 mb-lg-0 align-items-center nav-items">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active", style: "margin-right: 52px;" %>
        </li>
        <li class="nav-item">
          <%= link_to "Immunizations", root_path, class: "nav-link", style: "margin-right: 52px;" %>
        </li>
        <li class="nav-item">
          <%= link_to "Schedules", root_path, class: "nav-link", style: "margin-right: 52px;" %>
        </li>
        
        
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if medic_signed_in? %>
        
        <li class="nav-item">
          <%= button_to destroy_medic_session_path, method: :delete, class: "btn btn-outline-secondary nav-link" do %>
            <i class="fas fa-sign-out"></i> <!-- Font Awesome icon for Log out -->
          <% end %>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to new_medic_registration_path, class: "nav-link" do %>
            <i class="fas fa-user-plus"></i> <!-- Font Awesome icon for Sign up -->
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_medic_session_path, class: "nav-link" do %>
            <i class="fas fa-sign-in-alt"></i> <!-- Font Awesome icon for Log in -->
          <% end %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div class="sidebar-wrapper">
  <div class="d-flex flex-column align-items-center align-items-md-start px-3 pt-2 text-white min-vh-100 sidebar">
    <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-black text-decoration-none">
      <i class="fa-solid fa-user me-2"></i><span class="fs-5 d-none d-sm-inline"> Hi Medic </span>
    </a>
    <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
      
      <li class="mb-4"> <!-- Add margin bottom -->
        <a href="/dashboard/index" class="nav-link px-0 align-middle">
          <i class="fa-solid fa-list"></i> <span class="ms-1 d-none d-sm-inline">Dashboard</span></a>
      </li>
      <li class="mb-4"> <!-- Add margin bottom -->
        <a href="/children" class="nav-link px-0 align-middle">
          <i class="fa-solid fa-book"></i> <span class="ms-1 d-none d-sm-inline">Children</span> </a>
      </li>
      <li class="mb-4"> <!-- Add margin bottom -->
        <a href="/immunization_schedules" class="nav-link px-0 align-middle">
          <i class="fa-regular fa-building"></i> <span class="ms-1 d-none d-sm-inline">Schedules</span></a>
      </li>
      <li class="mb-4"> <!-- Add margin bottom -->
        <a href="/immunization_schedules" class="nav-link px-0 align-middle">
          <i class="fa-regular fa-sticky-note"></i> <span class="ms-1 d-none d-sm-inline">Stockouts</span></a>
      </li>
      <li class="mb-4"> <!-- Add margin bottom -->
        <a href="/profile" class="nav-link px-0 align-middle">
          <i class="fa-solid fa-user"></i> <span class="ms-1 d-none d-sm-inline">Profile</span> </a>
      </li>
    </ul>
    <hr>
  </div>
</div>